import { StyleSheet } from "react-native";
import { colors, radii, spacing, typography } from "@shellty/ui";

export const styles = StyleSheet.create({
  root: { flex: 1 },
  scrollArea: { flex: 1 },
  scrollContent: { gap: spacing[4], paddingBottom: spacing[4] },
  section: { gap: spacing[3] },
  grow: { flex: 1 },
  screenHeader: {
    gap: spacing[3],
    paddingBottom: spacing[1],
  },
  screenTitle: { ...typography.heading, color: colors.textPrimary },
  error: { ...typography.body, color: colors.error },
  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[3],
    borderRadius: radii.md,
    backgroundColor: colors.surfaceRose,
  },
  errorBannerText: {
    ...typography.body,
    color: colors.error,
    fontSize: 13,
    flex: 1,
  },
  errorBannerClose: { color: colors.error, fontSize: 22 },
  errorBannerDismiss: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  hero: {
    backgroundColor: colors.backgroundInverse,
    borderRadius: radii.xl,
    padding: spacing[5],
    gap: spacing[2],
  },
  eyebrow: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 12,
    letterSpacing: 1,
  },
  heroTitle: { ...typography.heading, color: colors.textInverse },
  heroText: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 14,
  },
  heroMeta: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 12,
  },
  progressTrack: {
    height: 7,
    borderRadius: 8,
    backgroundColor: colors.progressTrackInverse,
    overflow: "hidden",
    marginTop: spacing[2],
  },
  progressFill: { height: 7, backgroundColor: colors.accentTeal },
  todayOverview: {
    gap: spacing[3],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundCard,
  },
  todayOverviewRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
  },
  todayCourse: {
    ...typography.title,
    color: colors.actionSupport,
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.8,
  },
  todayOverviewTitle: {
    ...typography.title,
    color: colors.textPrimary,
    marginTop: spacing[1],
  },
  todayOverviewText: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  todayProgressBadge: {
    width: 58,
    height: 58,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 6,
    borderColor: colors.accentTeal,
    borderRadius: 29,
    backgroundColor: colors.surfaceTeal,
  },
  todayProgressValue: {
    ...typography.title,
    color: colors.success,
    fontSize: 12,
  },
  todayProgressTrack: {
    height: 8,
    overflow: "hidden",
    borderRadius: radii.pill,
    backgroundColor: colors.borderDefault,
  },
  todayProgressFill: {
    height: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.accentTeal,
  },
  todayOverviewMeta: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  recommendedCard: {
    gap: spacing[2],
    padding: spacing[5],
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
  },
  recommendedEyebrow: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 11,
    lineHeight: 16,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  recommendedTitle: {
    ...typography.heading,
    color: colors.textInverse,
  },
  recommendedText: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 13,
    lineHeight: 20,
  },
  recommendedMeta: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 12,
  },
  recommendedButton: {
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    marginTop: spacing[2],
    paddingHorizontal: spacing[4],
    borderRadius: radii.lg,
    backgroundColor: colors.actionPrimary,
  },
  recommendedButtonPressed: { opacity: 0.8 },
  recommendedButtonText: {
    ...typography.title,
    color: colors.textInverse,
    textAlign: "center",
  },
  planCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  planCardActive: { borderWidth: 2, borderColor: colors.actionPrimary },
  planIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: colors.surfaceTeal,
    alignItems: "center",
    justifyContent: "center",
  },
  planIconActive: { backgroundColor: colors.actionPrimary },
  planIconText: {
    color: colors.actionSupport,
    fontSize: 19,
    fontWeight: "800",
  },
  cardTitle: { ...typography.title, color: colors.textPrimary, fontSize: 15 },
  cardDetail: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  minutes: { ...typography.title, color: colors.actionPrimary, fontSize: 12 },
  thaiBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    borderRadius: radii.xl,
    backgroundColor: colors.surfaceTeal,
  },
  thaiGlyph: { ...typography.thai, fontSize: 34, color: colors.actionSupport },
  chevron: { fontSize: 26, color: colors.actionSupport },
  back: { ...typography.title, color: colors.actionPrimary, fontSize: 14 },
  heading: { ...typography.heading, color: colors.textPrimary },
  thaiText: { fontFamily: typography.thai.fontFamily },
  disclaimer: {
    ...typography.body,
    color: colors.warning,
    fontSize: 12,
    lineHeight: 18,
    padding: spacing[3],
    backgroundColor: colors.surfaceAmber,
    borderRadius: radii.md,
  },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: spacing[4],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
  },
  toggle: { color: colors.actionSupport, fontSize: 24 },
  thaiCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  audio: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.actionPrimary,
    alignItems: "center",
    justifyContent: "center",
  },
  audioText: { color: colors.textInverse, fontSize: 18 },
  glyph: { ...typography.thai, fontSize: 42, color: colors.textPrimary },
  transliteration: {
    ...typography.body,
    color: colors.actionPrimary,
    fontSize: 13,
  },
  example: { ...typography.thai, color: colors.actionSupport, fontSize: 13 },
  sectionLabel: {
    ...typography.title,
    color: colors.textSecondary,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginTop: spacing[2],
  },
  choice: {
    flexDirection: "row",
    gap: spacing[3],
    alignItems: "center",
    padding: spacing[4],
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  choiceActive: {
    borderWidth: 2,
    borderColor: colors.actionPrimary,
    backgroundColor: colors.surfaceBlue,
  },
  practiceHero: {
    padding: spacing[5],
    gap: spacing[2],
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
  },
  practiceTrust: {
    ...typography.body,
    color: colors.accentTealOnInverse,
    fontSize: 12,
    lineHeight: 18,
    marginTop: spacing[2],
  },
  sectionHint: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  scenarioCard: {
    gap: spacing[3],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
  },
  scenarioTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing[2],
  },
  scenarioContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
  },
  scenarioCategory: {
    ...typography.title,
    color: colors.actionSupport,
    fontSize: 10,
    letterSpacing: 0.7,
    textTransform: "uppercase",
  },
  scenarioMeta: {
    ...typography.title,
    color: colors.textSecondary,
    fontSize: 11,
  },
  scenarioRole: {
    ...typography.body,
    color: colors.actionPrimary,
    fontSize: 11,
    marginTop: spacing[2],
  },
  scenarioPreparation: {
    gap: spacing[3],
    padding: spacing[5],
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
  },
  preparationEyebrow: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 11,
    letterSpacing: 0.7,
  },
  preparationTitle: { ...typography.heading, color: colors.textInverse },
  preparationLabel: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 11,
    marginTop: spacing[2],
  },
  preparationBriefing: {
    ...typography.body,
    color: colors.textInverse,
    fontSize: 14,
    lineHeight: 22,
  },
  preparationText: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 13,
    lineHeight: 20,
    flex: 1,
  },
  preparationObjectives: { gap: spacing[2] },
  preparationObjective: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing[2],
  },
  preparationBullet: {
    ...typography.title,
    color: colors.accentTealOnInverse,
  },
  correctionMode: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
  },
  correctionModeActive: {
    borderColor: colors.actionPrimary,
    backgroundColor: colors.surfaceBlue,
  },
  startSummary: {
    padding: spacing[4],
    gap: spacing[1],
    borderRadius: radii.lg,
    backgroundColor: colors.surfaceTeal,
  },
  startSummaryLabel: {
    ...typography.title,
    color: colors.success,
    fontSize: 11,
    textTransform: "uppercase",
    letterSpacing: 0.7,
  },
  startSummaryText: { ...typography.body, color: colors.textPrimary },
  radio: { color: colors.actionPrimary, fontSize: 20 },
  mode: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.md,
  },
  primaryButton: {
    minHeight: 54,
    borderRadius: radii.lg,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.actionPrimary,
    marginTop: spacing[2],
  },
  primaryButtonText: { ...typography.title, color: colors.textInverse },
  chatHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: spacing[3],
    borderBottomWidth: 1,
    borderColor: colors.borderDefault,
  },
  conversationShell: { gap: spacing[3] },
  focusedTopBar: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing[3],
  },
  backButton: {
    minHeight: 44,
    justifyContent: "center",
    alignSelf: "flex-start",
  },
  backButtonText: {
    ...typography.title,
    color: colors.actionPrimary,
    fontSize: 13,
  },
  messageBudget: {
    minWidth: 68,
    alignItems: "center",
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    borderRadius: radii.pill,
    backgroundColor: colors.surfaceTeal,
  },
  messageBudgetValue: {
    ...typography.title,
    color: colors.success,
    fontSize: 14,
  },
  messageBudgetLabel: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 9,
  },
  conversationGoal: {
    gap: spacing[1],
    padding: spacing[4],
    borderRadius: radii.lg,
    backgroundColor: colors.surfaceBlue,
  },
  report: { ...typography.body, color: colors.error, fontSize: 11 },
  messageGroup: { maxWidth: "90%", gap: spacing[1], alignSelf: "flex-start" },
  learnerMessageGroup: { alignSelf: "flex-end", alignItems: "flex-end" },
  messageRole: {
    ...typography.title,
    color: colors.textSecondary,
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  bubble: { maxWidth: "88%", padding: spacing[4], borderRadius: radii.lg },
  learnerBubble: {
    alignSelf: "flex-end",
    backgroundColor: colors.actionPrimary,
    borderBottomRightRadius: 5,
  },
  assistantBubble: {
    alignSelf: "flex-start",
    backgroundColor: colors.backgroundCard,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderBottomLeftRadius: 5,
    padding: spacing[4],
    borderRadius: radii.lg,
  },
  learnerText: { ...typography.body, color: colors.textInverse },
  assistantText: { ...typography.body, color: colors.textPrimary },
  typingIndicator: {
    color: colors.textSecondary,
    fontSize: 16,
    marginTop: spacing[1],
    letterSpacing: 1,
  },
  inlineCorrection: {
    marginTop: spacing[3],
    padding: spacing[3],
    backgroundColor: colors.surfaceTeal,
    borderRadius: radii.md,
  },
  correctionEyebrow: {
    ...typography.title,
    color: colors.success,
    fontSize: 10,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  corrected: { ...typography.title, color: colors.success, fontSize: 13 },
  original: {
    ...typography.body,
    color: colors.error,
    fontSize: 13,
    textDecorationLine: "line-through",
  },
  composer: { flexDirection: "row", alignItems: "flex-end", gap: spacing[2] },
  composerArea: {
    gap: spacing[2],
    paddingTop: spacing[3],
    borderTopWidth: 1,
    borderColor: colors.borderDefault,
  },
  messageInput: {
    flex: 1,
    minHeight: 50,
    maxHeight: 120,
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    padding: spacing[3],
    ...typography.body,
  },
  send: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: colors.actionPrimary,
    alignItems: "center",
    justifyContent: "center",
  },
  sendDisabled: { opacity: 0.5 },
  sendText: { color: colors.textInverse, fontSize: 20 },
  privacyHint: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 10,
    lineHeight: 15,
  },
  fallbackNotice: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    padding: spacing[3],
    borderRadius: radii.md,
    backgroundColor: colors.surfaceBlue,
  },
  voiceAssessment: {
    gap: spacing[1],
    padding: spacing[3],
    borderRadius: radii.md,
    backgroundColor: colors.surfaceTeal,
  },
  recordingStatus: {
    ...typography.title,
    color: colors.error,
    fontSize: 12,
  },
  recordingActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing[3],
    padding: spacing[3],
    borderRadius: radii.md,
    backgroundColor: colors.surfaceBlue,
  },
  finishButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: spacing[4],
  },
  finishDisabled: { color: colors.textSecondary, opacity: 0.65 },
  finish: {
    ...typography.title,
    color: colors.actionPrimary,
    textAlign: "center",
    fontSize: 13,
  },
  summary: {
    alignItems: "center",
    gap: spacing[2],
    padding: spacing[6],
    backgroundColor: colors.surfaceTeal,
    borderRadius: radii.xl,
  },
  conversationSummary: {
    alignItems: "center",
    gap: spacing[2],
    padding: spacing[6],
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
  },
  summaryGlyph: {
    width: 54,
    height: 54,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 27,
    backgroundColor: colors.accentTeal,
  },
  summaryGlyphText: {
    ...typography.heading,
    color: colors.backgroundInverse,
  },
  summaryTitle: {
    ...typography.heading,
    color: colors.textInverse,
    textAlign: "center",
  },
  summaryRecommendation: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 13,
    lineHeight: 20,
    textAlign: "center",
  },
  summarySection: {
    gap: spacing[3],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
  },
  summaryRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: spacing[2],
  },
  summaryRowGlyph: { ...typography.title, color: colors.success },
  summaryRowText: { ...typography.body, color: colors.textPrimary, flex: 1 },
  wordGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing[2] },
  wordCard: {
    minWidth: "47%",
    flexGrow: 1,
    padding: spacing[3],
    borderRadius: radii.md,
    backgroundColor: colors.surfaceBlue,
  },
  nextPracticeCard: {
    gap: spacing[2],
    padding: spacing[4],
    borderRadius: radii.lg,
    backgroundColor: colors.surfaceTeal,
  },
  correction: {
    padding: spacing[4],
    gap: spacing[1],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
  },
  levelCard: {
    padding: spacing[5],
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
  },
  levelLabel: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 12,
  },
  levelNumber: {
    ...typography.display,
    color: colors.textInverse,
    marginTop: spacing[2],
  },
  metricGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing[3] },
  metric: {
    width: "47%",
    padding: spacing[4],
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  metricIcon: { fontSize: 18 },
  metricValue: {
    ...typography.heading,
    color: colors.textPrimary,
    marginTop: spacing[1],
  },
  metricLabel: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 11,
  },
  chart: {
    height: 110,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-around",
    padding: spacing[3],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
  },
  barColumn: {
    alignItems: "center",
    justifyContent: "flex-end",
    height: 90,
    gap: 4,
  },
  bar: { width: 18, borderRadius: 5, backgroundColor: colors.actionPrimary },
  barLabel: { ...typography.body, color: colors.textSecondary, fontSize: 9 },
  info: {
    padding: spacing[4],
    gap: spacing[1],
    backgroundColor: colors.surfaceBlue,
    borderRadius: radii.lg,
  },
  accountCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
  },
  accountAvatar: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 24,
    backgroundColor: colors.surfaceTeal,
  },
  accountAvatarText: {
    ...typography.title,
    color: colors.success,
    fontSize: 19,
  },
  accountEmail: {
    ...typography.body,
    color: colors.textPrimary,
    fontSize: 12,
    lineHeight: 18,
  },
  premiumHero: {
    padding: spacing[5],
    gap: spacing[2],
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
  },
  planPill: {
    alignSelf: "flex-start",
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1],
    borderRadius: radii.pill,
    backgroundColor: "rgba(127, 227, 216, 0.14)",
  },
  planPillText: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 11,
  },
  premiumTitle: { ...typography.heading, color: colors.textInverse },
  premiumText: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 13,
    lineHeight: 19,
  },
  usageText: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 12,
  },
  productCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  smallButton: {
    minHeight: 44,
    justifyContent: "center",
    maxWidth: 125,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    borderRadius: radii.md,
    backgroundColor: colors.actionPrimary,
  },
  smallButtonText: {
    ...typography.title,
    color: colors.textInverse,
    fontSize: 10,
    textAlign: "center",
  },
  settingsGroup: {
    overflow: "hidden",
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  settingRow: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
  },
  settingBorder: { borderBottomWidth: 1, borderColor: colors.borderSubtle },
  switchTrack: {
    width: 44,
    height: 26,
    borderRadius: 13,
    padding: 3,
    backgroundColor: colors.switchTrackOff,
  },
  switchTrackActive: { backgroundColor: colors.actionPrimary },
  switchThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.backgroundCard,
  },
  switchThumbActive: { alignSelf: "flex-end" },
  policyMeta: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 10,
    marginTop: spacing[2],
  },
  secondaryButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.actionPrimary,
    paddingHorizontal: spacing[3],
  },
  secondaryButtonText: { ...typography.title, color: colors.actionPrimary },
  dangerCard: {
    gap: spacing[3],
    padding: spacing[4],
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderRose,
    backgroundColor: colors.surfaceRose,
  },
  dangerButton: {
    minHeight: 48,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.lg,
    backgroundColor: colors.error,
    paddingHorizontal: spacing[3],
  },
  dangerButtonText: { ...typography.title, color: colors.textInverse },
  deletionLink: {
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  deletionLinkText: { ...typography.title, color: colors.error },
  successMessage: {
    ...typography.body,
    color: colors.success,
    backgroundColor: colors.surfaceTeal,
    borderRadius: radii.md,
    padding: spacing[3],
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
  },
  badgeIcon: { color: colors.accentGold, fontSize: 24 },
  listeningBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    backgroundColor: colors.surfaceBlueRaised,
    borderWidth: 1,
    borderColor: colors.borderBlue,
    borderRadius: radii.lg,
  },
  listeningIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.actionPrimary,
  },
  listeningIconText: { color: colors.textInverse, fontSize: 15, marginLeft: 2 },
  nav: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
    paddingVertical: spacing[2],
    marginTop: spacing[2],
  },
  navItem: {
    flex: 1,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
    gap: 2,
  },
  navIcon: { color: colors.textSecondary, fontSize: 20 },
  navLabel: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 10,
    lineHeight: 14,
  },
  navActive: { color: colors.actionPrimary, fontWeight: "800" },
  navDisabled: { opacity: 0.4 },
});
