import { StyleSheet } from "react-native";
import { colors, radii, spacing, typography } from "@shellty/ui";

export const styles = StyleSheet.create({
  root: { flex: 1 },
  scrollArea: { flex: 1 },
  scrollContent: { gap: spacing[4], paddingBottom: spacing[4] },
  section: { gap: spacing[3] },
  grow: { flex: 1 },
  error: { ...typography.body, color: colors.error },
  errorBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[3],
    borderRadius: radii.md,
    backgroundColor: colors.surfaceRose,
  },
  errorBannerText: {
    ...typography.body,
    color: colors.error,
    fontSize: 13,
    flex: 1,
  },
  errorBannerClose: { color: colors.error, fontSize: 22 },
  hero: {
    backgroundColor: colors.backgroundInverse,
    borderRadius: radii.xl,
    padding: spacing[5],
    gap: spacing[2],
  },
  eyebrow: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 12,
    letterSpacing: 1,
  },
  heroTitle: { ...typography.heading, color: colors.textInverse },
  heroText: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 14,
  },
  heroMeta: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 12,
  },
  progressTrack: {
    height: 7,
    borderRadius: 8,
    backgroundColor: colors.progressTrackInverse,
    overflow: "hidden",
    marginTop: spacing[2],
  },
  progressFill: { height: 7, backgroundColor: colors.accentTeal },
  planCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  planCardActive: { borderWidth: 2, borderColor: colors.actionPrimary },
  planIcon: {
    width: 46,
    height: 46,
    borderRadius: 14,
    backgroundColor: colors.surfaceTeal,
    alignItems: "center",
    justifyContent: "center",
  },
  planIconActive: { backgroundColor: colors.actionPrimary },
  planIconText: { color: colors.textInverse, fontSize: 19, fontWeight: "800" },
  cardTitle: { ...typography.title, color: colors.textPrimary, fontSize: 15 },
  cardDetail: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  minutes: { ...typography.title, color: colors.actionPrimary, fontSize: 12 },
  thaiBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    borderRadius: radii.xl,
    backgroundColor: colors.surfaceTeal,
  },
  thaiGlyph: { ...typography.thai, fontSize: 34, color: colors.actionSupport },
  chevron: { fontSize: 26, color: colors.actionSupport },
  back: { ...typography.title, color: colors.actionPrimary, fontSize: 14 },
  heading: { ...typography.heading, color: colors.textPrimary },
  thaiText: { fontFamily: typography.thai.fontFamily },
  disclaimer: {
    ...typography.body,
    color: colors.warning,
    fontSize: 12,
    lineHeight: 18,
    padding: spacing[3],
    backgroundColor: colors.surfaceAmber,
    borderRadius: radii.md,
  },
  toggleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: spacing[4],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
  },
  toggle: { color: colors.actionSupport, fontSize: 24 },
  thaiCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  audio: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.actionPrimary,
    alignItems: "center",
    justifyContent: "center",
  },
  audioText: { color: colors.textInverse, fontSize: 18 },
  glyph: { ...typography.thai, fontSize: 42, color: colors.textPrimary },
  transliteration: {
    ...typography.body,
    color: colors.actionPrimary,
    fontSize: 13,
  },
  example: { ...typography.thai, color: colors.actionSupport, fontSize: 13 },
  sectionLabel: {
    ...typography.title,
    color: colors.textSecondary,
    fontSize: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginTop: spacing[2],
  },
  choice: {
    flexDirection: "row",
    gap: spacing[3],
    alignItems: "center",
    padding: spacing[4],
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  choiceActive: {
    borderWidth: 2,
    borderColor: colors.actionPrimary,
    backgroundColor: colors.surfaceBlue,
  },
  radio: { color: colors.actionPrimary, fontSize: 20 },
  mode: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.md,
  },
  primaryButton: {
    minHeight: 54,
    borderRadius: radii.lg,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.actionPrimary,
    marginTop: spacing[2],
  },
  primaryButtonText: { ...typography.title, color: colors.textInverse },
  chatHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: spacing[3],
    borderBottomWidth: 1,
    borderColor: colors.borderDefault,
  },
  report: { ...typography.body, color: colors.error, fontSize: 11 },
  bubble: { maxWidth: "88%", padding: spacing[4], borderRadius: radii.lg },
  learnerBubble: {
    alignSelf: "flex-end",
    backgroundColor: colors.actionPrimary,
    borderBottomRightRadius: 5,
  },
  assistantBubble: {
    alignSelf: "flex-start",
    backgroundColor: colors.backgroundCard,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderBottomLeftRadius: 5,
    padding: spacing[4],
    borderRadius: radii.lg,
  },
  learnerText: { ...typography.body, color: colors.textInverse },
  assistantText: { ...typography.body, color: colors.textPrimary },
  typingIndicator: {
    color: colors.textSecondary,
    fontSize: 16,
    marginTop: spacing[1],
    letterSpacing: 1,
  },
  inlineCorrection: {
    marginTop: spacing[3],
    padding: spacing[3],
    backgroundColor: colors.surfaceTeal,
    borderRadius: radii.md,
  },
  corrected: { ...typography.title, color: colors.success, fontSize: 13 },
  original: {
    ...typography.body,
    color: colors.error,
    fontSize: 13,
    textDecorationLine: "line-through",
  },
  composer: { flexDirection: "row", alignItems: "flex-end", gap: spacing[2] },
  messageInput: {
    flex: 1,
    minHeight: 50,
    maxHeight: 120,
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    padding: spacing[3],
    ...typography.body,
  },
  send: {
    width: 50,
    height: 50,
    borderRadius: 16,
    backgroundColor: colors.actionPrimary,
    alignItems: "center",
    justifyContent: "center",
  },
  sendDisabled: { opacity: 0.5 },
  sendText: { color: colors.textInverse, fontSize: 20 },
  finish: {
    ...typography.title,
    color: colors.actionPrimary,
    textAlign: "center",
    fontSize: 13,
  },
  summary: {
    alignItems: "center",
    gap: spacing[2],
    padding: spacing[6],
    backgroundColor: colors.surfaceTeal,
    borderRadius: radii.xl,
  },
  correction: {
    padding: spacing[4],
    gap: spacing[1],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
  },
  levelCard: {
    padding: spacing[5],
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
  },
  levelLabel: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 12,
  },
  levelNumber: {
    ...typography.display,
    color: colors.textInverse,
    marginTop: spacing[2],
  },
  metricGrid: { flexDirection: "row", flexWrap: "wrap", gap: spacing[3] },
  metric: {
    width: "47%",
    padding: spacing[4],
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
    borderWidth: 1,
    borderColor: colors.borderDefault,
  },
  metricIcon: { fontSize: 18 },
  metricValue: {
    ...typography.heading,
    color: colors.textPrimary,
    marginTop: spacing[1],
  },
  metricLabel: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 11,
  },
  chart: {
    height: 110,
    flexDirection: "row",
    alignItems: "flex-end",
    justifyContent: "space-around",
    padding: spacing[3],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
  },
  barColumn: {
    alignItems: "center",
    justifyContent: "flex-end",
    height: 90,
    gap: 4,
  },
  bar: { width: 18, borderRadius: 5, backgroundColor: colors.actionPrimary },
  barLabel: { ...typography.body, color: colors.textSecondary, fontSize: 9 },
  info: {
    padding: spacing[4],
    gap: spacing[1],
    backgroundColor: colors.surfaceBlue,
    borderRadius: radii.lg,
  },
  premiumHero: {
    padding: spacing[5],
    gap: spacing[2],
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
  },
  planPill: {
    alignSelf: "flex-start",
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1],
    borderRadius: radii.pill,
    backgroundColor: "rgba(127, 227, 216, 0.14)",
  },
  planPillText: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 11,
  },
  premiumTitle: { ...typography.heading, color: colors.textInverse },
  premiumText: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 13,
    lineHeight: 19,
  },
  usageText: {
    ...typography.title,
    color: colors.accentTealOnInverse,
    fontSize: 12,
  },
  productCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  smallButton: {
    maxWidth: 125,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    borderRadius: radii.md,
    backgroundColor: colors.actionPrimary,
  },
  smallButtonText: {
    ...typography.title,
    color: colors.textInverse,
    fontSize: 10,
    textAlign: "center",
  },
  settingsGroup: {
    overflow: "hidden",
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  settingRow: {
    minHeight: 70,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    paddingHorizontal: spacing[4],
    paddingVertical: spacing[3],
  },
  settingBorder: { borderBottomWidth: 1, borderColor: colors.borderSubtle },
  switchTrack: {
    width: 44,
    height: 26,
    borderRadius: 13,
    padding: 3,
    backgroundColor: colors.switchTrackOff,
  },
  switchTrackActive: { backgroundColor: colors.actionPrimary },
  switchThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.backgroundCard,
  },
  switchThumbActive: { alignSelf: "flex-end" },
  policyMeta: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 10,
    marginTop: spacing[2],
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
  },
  badgeIcon: { color: colors.accentGold, fontSize: 24 },
  listeningBanner: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    backgroundColor: colors.surfaceBlueRaised,
    borderWidth: 1,
    borderColor: colors.borderBlue,
    borderRadius: radii.lg,
  },
  listeningIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.actionPrimary,
  },
  listeningIconText: { color: colors.textInverse, fontSize: 15, marginLeft: 2 },
  nav: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
    borderRadius: radii.lg,
    paddingVertical: spacing[2],
    marginTop: spacing[2],
  },
  navItem: { flex: 1, alignItems: "center", gap: 2 },
  navIcon: { color: colors.textSecondary, fontSize: 20 },
  navLabel: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 10,
    lineHeight: 14,
  },
  navActive: { color: colors.actionPrimary, fontWeight: "800" },
});
