import { StyleSheet } from "react-native";
import { colors, radii, spacing, typography } from "@shellty/ui";

export const styles = StyleSheet.create({
  flow: { gap: spacing[3] },
  flex: { flex: 1 },
  title: { ...typography.heading, color: colors.textPrimary },
  eyebrow: {
    ...typography.title,
    color: colors.textSecondary,
    fontSize: 12,
    letterSpacing: 0.7,
  },
  courseHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing[3],
  },
  level: {
    ...typography.title,
    color: colors.actionPrimary,
    backgroundColor: colors.surfaceBlue,
    borderRadius: radii.pill,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    fontSize: 13,
  },
  darkCard: {
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
    padding: spacing[5],
    gap: spacing[2],
  },
  darkTitle: { ...typography.title, color: colors.textInverse },
  darkBody: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 13,
  },
  moduleCard: {
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundInverse,
    padding: spacing[4],
  },
  moduleTitle: { ...typography.title, color: colors.textInverse },
  lessonCard: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  lessonCardActive: { borderWidth: 2, borderColor: colors.actionPrimary },
  lessonIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: colors.actionPrimary,
  },
  lessonIconText: { color: colors.textInverse, fontSize: 18 },
  optionTitle: { ...typography.title, color: colors.textPrimary },
  detail: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  chevron: { color: colors.actionPrimary, fontSize: 24 },
  reviewBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: spacing[4],
    borderRadius: radii.lg,
    backgroundColor: colors.surfaceTeal,
  },
  reviewCount: {
    ...typography.title,
    color: colors.textInverse,
    backgroundColor: colors.actionSupport,
    borderRadius: radii.pill,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
  },
  progressHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
  },
  close: {
    width: 44,
    height: 44,
    borderRadius: radii.md,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  closeText: { color: colors.textSecondary, fontSize: 24 },
  progressTrack: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    overflow: "hidden",
    backgroundColor: colors.borderDefault,
  },
  progressValue: { height: "100%", backgroundColor: colors.accentTeal },
  lessonContext: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    paddingBottom: spacing[1],
  },
  lessonTitle: {
    ...typography.title,
    color: colors.textPrimary,
  },
  lessonMeta: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    marginTop: spacing[1],
  },
  exerciseInstruction: {
    ...typography.heading,
    color: colors.textPrimary,
    fontSize: 21,
    lineHeight: 28,
  },
  promptCard: {
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
    padding: spacing[6],
    gap: spacing[4],
  },
  prompt: {
    ...typography.heading,
    color: colors.textInverse,
    textAlign: "center",
  },
  promptTranslation: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 14,
    lineHeight: 21,
    textAlign: "center",
  },
  promptDictionarySelection: {
    color: colors.linkOnInverse,
    textDecorationLine: "underline",
  },
  listeningPromptIcon: {
    width: 58,
    height: 58,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 29,
    backgroundColor: colors.actionPrimary,
  },
  listeningPromptIconText: {
    color: colors.textInverse,
    fontSize: 22,
    marginLeft: 3,
  },
  listeningActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing[2],
  },
  wordTarget: {
    minHeight: 44,
    justifyContent: "center",
    paddingHorizontal: spacing[1],
  },
  thaiPromptDisplay: {
    ...typography.thai,
    color: colors.textInverse,
    fontSize: 24,
    lineHeight: 38,
    textAlign: "center",
  },
  options: { gap: spacing[3] },
  answerPreview: {
    borderRadius: radii.lg,
    padding: spacing[4],
    gap: spacing[2],
    backgroundColor: colors.surfaceTeal,
  },
  answerPreviewLabel: {
    ...typography.body,
    fontSize: 12,
    color: colors.actionSupport,
    textTransform: "uppercase",
  },
  answerPreviewText: {
    ...typography.title,
    color: colors.textPrimary,
  },
  celebration: { fontSize: 56, textAlign: "center" },
  option: {
    minHeight: 56,
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.borderDefault,
    borderRadius: radii.lg,
    padding: spacing[4],
    backgroundColor: colors.backgroundCard,
  },
  optionSelected: {
    borderColor: colors.accentTeal,
    backgroundColor: colors.surfaceTeal,
  },
  optionSelectedText: { color: colors.actionSupport },
  optionExpected: {
    borderColor: colors.actionSupport,
    backgroundColor: colors.surfaceTeal,
  },
  optionExpectedText: { color: colors.success },
  optionRejected: {
    borderColor: colors.error,
    backgroundColor: colors.surfaceRose,
  },
  optionRejectedText: { color: colors.error },
  input: {
    minHeight: 54,
    borderWidth: 2,
    borderColor: colors.actionPrimary,
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
    paddingHorizontal: spacing[4],
    ...typography.body,
    color: colors.textPrimary,
  },
  correct: {
    borderRadius: radii.lg,
    padding: spacing[4],
    backgroundColor: colors.surfaceTeal,
  },
  incorrect: {
    borderRadius: radii.lg,
    padding: spacing[4],
    backgroundColor: colors.surfaceRose,
  },
  feedbackPanel: {
    gap: spacing[3],
    padding: spacing[4],
    borderWidth: 1,
    borderRadius: radii.lg,
  },
  feedbackCorrect: {
    borderColor: colors.actionSupport,
    backgroundColor: colors.surfaceTeal,
  },
  feedbackPartial: {
    borderColor: colors.warning,
    backgroundColor: colors.surfaceAmber,
  },
  feedbackIncorrect: {
    borderColor: colors.borderRose,
    backgroundColor: colors.surfaceRoseDeep,
  },
  feedbackHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
  },
  feedbackIcon: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 18,
  },
  feedbackIconCorrect: { backgroundColor: colors.actionSupport },
  feedbackIconPartial: { backgroundColor: colors.warning },
  feedbackIconIncorrect: { backgroundColor: colors.error },
  feedbackIconText: {
    ...typography.title,
    color: colors.textInverse,
  },
  feedbackTitle: { ...typography.title, color: colors.textPrimary },
  feedbackBody: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 13,
  },
  expectedAnswerCard: {
    gap: spacing[1],
    padding: spacing[3],
    borderRadius: radii.md,
    backgroundColor: colors.backgroundCard,
  },
  expectedAnswerLabel: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    textTransform: "uppercase",
  },
  expectedAnswerText: {
    ...typography.title,
    color: colors.textPrimary,
    fontSize: 14,
  },
  transcriptCard: {
    gap: spacing[2],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.borderBlue,
    borderRadius: radii.lg,
    backgroundColor: colors.surfaceBlue,
  },
  transcriptText: {
    ...typography.title,
    color: colors.textPrimary,
    textAlign: "center",
  },
  thaiTranscript: {
    ...typography.thai,
    color: colors.textPrimary,
    fontSize: 22,
    lineHeight: 36,
    textAlign: "center",
  },
  transcriptWords: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing[1],
  },
  transcriptWord: {
    ...typography.body,
    color: colors.actionPrimary,
    textDecorationLine: "underline",
  },
  dictionaryCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
    padding: spacing[5],
    gap: spacing[3],
  },
  dictionaryTerm: { ...typography.heading, color: colors.actionPrimary },
  dynamicBadge: {
    ...typography.body,
    alignSelf: "flex-start",
    color: colors.actionSupport,
    backgroundColor: colors.surfaceTeal,
    borderRadius: radii.pill,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1],
    fontSize: 11,
  },
  dictionaryMeaning: { ...typography.title, color: colors.textPrimary },
  dictionaryModalSafe: {
    flex: 1,
    backgroundColor: colors.backgroundApp,
  },
  dictionaryModalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    paddingHorizontal: spacing[5],
    paddingVertical: spacing[3],
    borderBottomWidth: 1,
    borderBottomColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  dictionaryModalTitle: {
    ...typography.heading,
    color: colors.textPrimary,
  },
  dictionaryModalContent: {
    gap: spacing[4],
    padding: spacing[5],
    paddingBottom: spacing[8],
  },
  dictionaryNotice: {
    gap: spacing[2],
    padding: spacing[3],
    borderRadius: radii.md,
    backgroundColor: colors.surfaceAmber,
  },
  dictionaryNoticeText: {
    ...typography.body,
    color: colors.warning,
    fontSize: 12,
    lineHeight: 18,
  },
  dictionaryTransliteration: {
    ...typography.thai,
    color: colors.actionSupport,
  },
  dictionarySection: {
    gap: spacing[2],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
  },
  dictionarySectionLabel: {
    ...typography.title,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
    textTransform: "uppercase",
  },
  dictionaryTranslation: {
    ...typography.title,
    color: colors.actionPrimary,
  },
  speechRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing[2] },
  primaryButton: {
    minHeight: 54,
    alignSelf: "stretch",
    flexDirection: "row",
    gap: spacing[2],
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.lg,
    backgroundColor: colors.actionPrimary,
    paddingHorizontal: spacing[4],
    marginTop: spacing[2],
  },
  primaryButtonText: {
    ...typography.title,
    color: colors.textInverse,
    textAlign: "center",
  },
  smallButton: {
    minHeight: 44,
    justifyContent: "center",
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
    paddingHorizontal: spacing[3],
  },
  smallButtonActive: {
    borderColor: colors.actionPrimary,
    backgroundColor: colors.surfaceBlue,
  },
  smallButtonText: {
    ...typography.body,
    color: colors.actionPrimary,
    fontSize: 12,
  },
  smallButtonTextActive: { fontWeight: "700" },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.8 },
  badge: {
    alignSelf: "flex-start",
    ...typography.title,
    color: colors.actionSupport,
    backgroundColor: colors.surfaceTeal,
    borderRadius: radii.pill,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    fontSize: 12,
  },
  skip: { minHeight: 44, alignItems: "center", justifyContent: "center" },
  summary: {
    alignItems: "center",
    gap: spacing[4],
    paddingVertical: spacing[8],
  },
  summaryTitle: {
    ...typography.heading,
    color: colors.textPrimary,
    textAlign: "center",
  },
  summaryCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 10,
    borderColor: colors.accentTeal,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.backgroundCard,
  },
  summaryScore: { ...typography.display, color: colors.actionSupport },
  summaryScoreLabel: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  summaryMetrics: {
    alignSelf: "stretch",
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing[3],
  },
  summaryMetric: {
    flexGrow: 1,
    flexBasis: 130,
    gap: spacing[1],
    padding: spacing[4],
    borderWidth: 1,
    borderColor: colors.borderDefault,
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
  },
  summaryMetricValue: {
    ...typography.heading,
    color: colors.actionPrimary,
  },
  summaryMetricLabel: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 11,
    lineHeight: 16,
  },
  ratingRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing[2],
  },
  message: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    borderRadius: radii.md,
    padding: spacing[3],
    backgroundColor: colors.surfaceRose,
  },
  messageText: {
    ...typography.body,
    color: colors.error,
    fontSize: 12,
    flex: 1,
  },
  messageAction: { color: colors.error, fontSize: 22 },
  messageDismiss: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
});
