import { StyleSheet } from "react-native";
import { colors, radii, spacing, typography } from "@shellty/ui";

export const styles = StyleSheet.create({
  flow: { gap: spacing[3] },
  flex: { flex: 1 },
  title: { ...typography.heading, color: colors.textPrimary },
  eyebrow: {
    ...typography.title,
    color: colors.textSecondary,
    fontSize: 12,
    letterSpacing: 0.7,
  },
  courseHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing[3],
  },
  level: {
    ...typography.title,
    color: colors.actionPrimary,
    backgroundColor: colors.surfaceBlue,
    borderRadius: radii.pill,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    fontSize: 13,
  },
  darkCard: {
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
    padding: spacing[5],
    gap: spacing[2],
  },
  darkTitle: { ...typography.title, color: colors.textInverse },
  darkBody: {
    ...typography.body,
    color: colors.textOnInverseMuted,
    fontSize: 13,
  },
  moduleCard: {
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundInverse,
    padding: spacing[4],
  },
  moduleTitle: { ...typography.title, color: colors.textInverse },
  lessonCard: {
    minHeight: 74,
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    padding: spacing[4],
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  lessonCardActive: { borderWidth: 2, borderColor: colors.actionPrimary },
  lessonIcon: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    backgroundColor: colors.actionPrimary,
  },
  lessonIconText: { color: colors.textInverse, fontSize: 18 },
  optionTitle: { ...typography.title, color: colors.textPrimary },
  detail: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
  },
  chevron: { color: colors.actionPrimary, fontSize: 24 },
  reviewBanner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: spacing[4],
    borderRadius: radii.lg,
    backgroundColor: colors.surfaceTeal,
  },
  reviewCount: {
    ...typography.title,
    color: colors.textInverse,
    backgroundColor: colors.actionSupport,
    borderRadius: radii.pill,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
  },
  progressHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
  },
  close: {
    width: 40,
    height: 40,
    borderRadius: radii.md,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
  },
  closeText: { color: colors.textSecondary, fontSize: 24 },
  progressTrack: {
    flex: 1,
    height: 8,
    borderRadius: 4,
    overflow: "hidden",
    backgroundColor: colors.borderDefault,
  },
  progressValue: { height: "100%", backgroundColor: colors.accentTeal },
  promptCard: {
    borderRadius: radii.xl,
    backgroundColor: colors.backgroundInverse,
    padding: spacing[6],
    gap: spacing[4],
  },
  prompt: {
    ...typography.heading,
    color: colors.textInverse,
    textAlign: "center",
  },
  words: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing[2],
  },
  word: {
    ...typography.body,
    color: colors.linkOnInverse,
    textDecorationLine: "underline",
  },
  options: { gap: spacing[3] },
  option: {
    minHeight: 56,
    justifyContent: "center",
    borderWidth: 2,
    borderColor: colors.borderDefault,
    borderRadius: radii.lg,
    padding: spacing[4],
    backgroundColor: colors.backgroundCard,
  },
  optionSelected: {
    borderColor: colors.accentTeal,
    backgroundColor: colors.surfaceTeal,
  },
  optionSelectedText: { color: colors.actionSupport },
  input: {
    minHeight: 54,
    borderWidth: 2,
    borderColor: colors.actionPrimary,
    borderRadius: radii.lg,
    backgroundColor: colors.backgroundCard,
    paddingHorizontal: spacing[4],
    ...typography.body,
    color: colors.textPrimary,
  },
  correct: {
    borderRadius: radii.lg,
    padding: spacing[4],
    backgroundColor: colors.surfaceTeal,
  },
  incorrect: {
    borderRadius: radii.lg,
    padding: spacing[4],
    backgroundColor: colors.surfaceRose,
  },
  feedbackTitle: { ...typography.title, color: colors.textPrimary },
  feedbackBody: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 13,
  },
  dictionaryCard: {
    borderRadius: radii.xl,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
    padding: spacing[5],
    gap: spacing[3],
  },
  dictionaryTerm: { ...typography.heading, color: colors.actionPrimary },
  dynamicBadge: {
    ...typography.body,
    alignSelf: "flex-start",
    color: colors.actionSupport,
    backgroundColor: colors.surfaceTeal,
    borderRadius: radii.pill,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[1],
    fontSize: 11,
  },
  dictionaryMeaning: { ...typography.title, color: colors.textPrimary },
  speechRow: { flexDirection: "row", flexWrap: "wrap", gap: spacing[2] },
  primaryButton: {
    minHeight: 54,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: radii.lg,
    backgroundColor: colors.actionPrimary,
    paddingHorizontal: spacing[4],
    marginTop: spacing[2],
  },
  primaryButtonText: {
    ...typography.title,
    color: colors.textInverse,
    textAlign: "center",
  },
  smallButton: {
    minHeight: 44,
    justifyContent: "center",
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.borderDefault,
    backgroundColor: colors.backgroundCard,
    paddingHorizontal: spacing[3],
  },
  smallButtonActive: {
    borderColor: colors.actionPrimary,
    backgroundColor: colors.surfaceBlue,
  },
  smallButtonText: {
    ...typography.body,
    color: colors.actionPrimary,
    fontSize: 12,
  },
  smallButtonTextActive: { fontWeight: "700" },
  disabled: { opacity: 0.45 },
  pressed: { opacity: 0.8 },
  badge: {
    alignSelf: "flex-start",
    ...typography.title,
    color: colors.actionSupport,
    backgroundColor: colors.surfaceTeal,
    borderRadius: radii.pill,
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    fontSize: 12,
  },
  skip: { minHeight: 44, alignItems: "center", justifyContent: "center" },
  summary: {
    alignItems: "center",
    gap: spacing[4],
    paddingVertical: spacing[8],
  },
  summaryCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 10,
    borderColor: colors.accentTeal,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.backgroundCard,
  },
  summaryScore: { ...typography.display, color: colors.actionSupport },
  ratingRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: spacing[2],
  },
  message: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing[3],
    borderRadius: radii.md,
    padding: spacing[3],
    backgroundColor: colors.surfaceRose,
  },
  messageText: {
    ...typography.body,
    color: colors.error,
    fontSize: 12,
    flex: 1,
  },
  messageAction: { color: colors.error, fontSize: 22 },
});
